# Ref: https://forum.opnsense.org/index.php?topic=15756.0
# Ref: https://blog.xirion.net/posts/metallb-opnsense/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddns-updater

commonLabels:
  cluster: kubernetes-01

resources:
  - ../base
  - externalsecret-cloudflare-credentials.yaml
