apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - clusterissuer-self-signed.yaml
  - clusterissuer-staging.yaml
  - clusterissuer-production.yaml
  - externalsecret-cloudflare-api-token.yaml
