apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt
spec:
  secretName: zigbee2mqtt-tls
  dnsNames:
    - zigbee2mqtt.tools.internal.place
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
