apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: zigbee2mqtt-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret.yaml: |
          mqtt_password: {{ .ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD }}
          advanced_network_key: {{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}
  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: NATS_USERS_CREDENTIALS_PASSWORD_ZIGBEE2MQTT

    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
      remoteRef:
        key: ZIGBEE2MQTT_NETWORK_KEY
