apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: zigbee2mqtt-credentials
    creationPolicy: Owner

  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_USER
      remoteRef:
        key: ZIGBEE2MQTT_CONFIG_MQTT_USER

    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
