apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: zigbee2mqtt
  meta.helm.sh/release-namespace: zigbee2mqtt

replicas:
  - name: zigbee2mqtt
    count: 1

images:
  - name: koenkk/zigbee2mqtt:latest
    newTag: 1.40.2

resources:
  - ../base
  - configmap-env.yaml
  - externalsecret-zigbee2mqtt-credentials.yaml
  - certificate.yaml
  - ingress.yml

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: compute-13
    target:
      kind: Deployment