apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt

commonLabels:
  cluster: kubernetes-01

replicas:
  - name: zigbee2mqtt
    count: 1

images:
  - name: koenkk/zigbee2mqtt:latest
    newTag: 1.40.2

resources:
  - ../base
  - configmap-env.yaml
  - externalsecret-zigbee2mqtt-credentials.yaml
  - service.yml
  - certificate.yaml
  - ingress.yml
