apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  replicas: 1
  selector: {}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {}
    spec:
      restartPolicy: Always

      # Substitute variables inside template file with their real values from environment vars
      # Done this way as the actual application does not support environment variables
      initContainers:
        - name: config-variables-expansion
          image: alpine
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              apk add --no-cache gettext
              mkdir -p /etc/cloudflare-ddns
              envsubst < /tmp/cloudflare-ddns/config.template.json > /etc/cloudflare-ddns/config.json
              cat /etc/cloudflare-ddns/config.json
              ls -alh /etc/cloudflare-ddns/
          envFrom:
            - secretRef:
                name: cloudflare-credentials
          volumeMounts:
            - mountPath: '/tmp/cloudflare-ddns/'
              name: config-cloudflare-ddns
              readOnly: true
            - mountPath: '/etc/cloudflare-ddns'
              name: config-data

      containers:
        - name: cloudflare-ddns
          image: timothyjmiller/cloudflare-ddns:latest
          env:
            - name: CONFIG_PATH
              value: '/etc/cloudflare-ddns/'
          volumeMounts:
            - mountPath: '/etc/cloudflare-ddns'
              name: config-data
      volumes:
        - name: config-cloudflare-ddns
          configMap:
            name: config-cloudflare-ddns

        # A place to store config between initContainers and the main container
        - name: config-data
          emptyDir: {}

