apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-ddns

commonLabels:
  app.kubernetes.io/name: cloudflare-ddns

resources:
  - namespace.yaml
  - deployment.yaml
  - configmap-config.yaml
