# DISCLAIMER: THESE VALUES ARE FOR PRODUCTION PURPOSES ONLY.
# PLEASE, DON'T DO DIRTY THINGS

# Ref: https://rclone.org/commands/rclone_serve_webdav/
# Ref: https://rclone.org/commands/rclone_obscure/
# Ref: https://rclone.org/sftp/

rclone:

  controllers:

    application:
      type: deployment
      replicas: 2

      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        rclone:
          image:
            repository: rclone/rclone
            tag: 1.68.1
          command:
            - rclone
          args:
            - serve
            - webdav
            - --addr
            - :8080
            - --config
            - /etc/rclone.conf
            - storage-01-root-dir:/Gallery

          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-credentials"

  configMaps:
    config:
      enabled: true
      annotations: {}
      data:
        rclone.conf: |
          [storage-01]
          type = sftp
          host = storage-01.internal.place
          port = 22
          shell_type = unix
          md5sum_command = md5sum
          sha1sum_command = sha1sum

          [storage-01-root-dir]
          type = alias
          remote = storage-01:/mnt/pool0/shared/alby.hernandez

  service:
    rclone:
      controller: application
      type: ClusterIP
      ports:
        webdav:
          port: 8080

  ingress:
    application:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
      hosts:
        - host: &host webdav.tools.internal.place
          paths:
            - path: /
              pathType: Prefix
              service:
                name: rclone
                port: 8080
      tls:
      - hosts:
          - *host
        secretName: webdav-tls

  persistence:
    config-volume:
      enabled: true
      name: rclone-config
      type: configMap
      advancedMounts:
        application: # Controller
          rclone: # Container
            - path: /etc/rclone.conf
              readOnly: true
              mountPropagation: None
              subPath: rclone.conf

  rawResources:
    credentials:
      enabled: true
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      spec:
        spec: # TODO: Open an issue to fix this duplicated key
          secretStoreRef:
            kind: ClusterSecretStore
            name: gitlab-secret-store

          target:
            name: rclone-credentials
            creationPolicy: Owner

          data:
            - secretKey: RCLONE_USER
              remoteRef:
                key: RCLONE_WEBDAV_USER_01

            # Ref: https://rclone.org/commands/rclone_obscure/
            - secretKey: RCLONE_PASS
              remoteRef:
                key: RCLONE_WEBDAV_PASS_01

            - secretKey: RCLONE_SFTP_USER
              remoteRef:
                key: RCLONE_SFTP_USER_ALBY_HERNANDEZ

            - secretKey: RCLONE_SFTP_PASS
              remoteRef:
                key: RCLONE_SFTP_PASS_ALBY_HERNANDEZ

    certificate:
      enabled: true
      apiVersion: cert-manager.io/v1
      kind: Certificate
      spec:
        spec: # TODO: Open an issue to fix this duplicated key
          secretName: webdav-tls
          dnsNames:
            - webdav.tools.internal.place
          issuerRef:
            name: letsencrypt-production
            kind: ClusterIssuer
            group: cert-manager.io
