# DISCLAIMER: THESE VALUES ARE FOR PRODUCTION PURPOSES ONLY.
# PLEASE, DON'T DO DIRTY THINGS

csi-driver-s3:

  storageClass:
    create: true
    name: standard-s3
    singleBucket: backups-kubernetes

  secret:
    create: false
    name: csi-driver-s3-credentials
