apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-02
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: cert-manager-extra
  meta.helm.sh/release-namespace: cert-manager

resources:
  - ../local

  - clusterissuer-staging.yaml
  - clusterissuer-production.yaml
