apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - applications

patches:
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    path: overlays/patchFluxKustomizeController.yaml
