apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {}
  template:
    spec:
#      securityContext:
#        fsGroup: 33
#        fsGroupChangePolicy: "OnRootMismatch"
      restartPolicy: Always
#      initContainers:
#        - name: merge-configs
#          image: linuxserver/yq
#          command: [ "/bin/sh", "-c", "cp /config/cassandra.yaml /config/cassandra/" ]
#          volumeMounts:
#            - name: tmp-config
#              mountPath: /config/cassandra/
#            - name: cassandraconfig
#              mountPath: /config/
      containers:
      - name: home-assistant
        image: "ghcr.io/home-assistant/home-assistant:latest"
        imagePullPolicy: IfNotPresent

        # Needed to interact with USB devices connected to the node
        securityContext:
          privileged: true

        envFrom:
          - configMapRef:
              name: home-assistant-env
        ports:
          - name: http
            containerPort: 8123
            protocol: TCP

        livenessProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10

        readinessProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10

        startupProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5

        volumeMounts:
          - name: runudev
            mountPath: /run/udev
            readOnly: true

          - name: ha-config-data
            mountPath: /config

          - mountPath: /config/configuration.yaml
            subPath: configuration.yaml
            name: configmap-file

#          - mountPath: /config/automations.yaml
#            subPath: automations.yaml
#            name: configmap-file
#
#          - mountPath: /config/scripts.yaml
#            subPath: scripts.yaml
#            name: configmap-file

#          - mountPath: /config/python_scripts.yaml
#            subPath: python_scripts.yaml
#            name: configmap-file

      volumes:
        # Only required for auto-detecting the port and some adapters like ConBee
        - name: runudev
          hostPath:
            path: /run/udev

        - name: ha-config-data
          persistentVolumeClaim:
            claimName: home-assistant-config-data

        - name: configmap-file
          configMap:
            name: home-assistant-config
