{{- range $key, $value := .Values.customComponents.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "meta-mongodb.fullname" $ }}-{{ $key }}
  labels:
    {{- include "meta-mongodb.labels" $ | nindent 4 }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ toYaml $value.spec | nindent 2 }}
---
{{- end }}
