apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada-controller

commonLabels:
  cluster: kubernetes-01
  app.kubernetes.io/name: omada-controller

resources:
  - namespace.yaml
  #- persistentvolumeclaim/logs.yaml
  #- persistentvolumeclaim/data.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
