apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forecastle

commonLabels:
  cluster: kubernetes-01
  app.kubernetes.io/name: forecastle

resources:
  # Infrastructure
  - opnsense.yaml
  - storage-01.yaml
  - compute-10.yaml

  # Applications
  - congatudo.yaml
  - vaultwarden.yaml
