apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omada-user-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: omada-user-credentials
  data:
    - secretKey: OMADA_USERS_CREDENTIALS_USERNAME_ADMIN
      remoteRef:
        key: OMADA_USERS_CREDENTIALS_USERNAME_ADMIN
    - secretKey: OMADA_USERS_CREDENTIALS_PASSWORD_ADMIN
      remoteRef:
        key: OMADA_USERS_CREDENTIALS_PASSWORD_ADMIN
