apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-user-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: mongodb-user-credentials
  data:
    - secretKey: MONGODB_USERS_CREDENTIALS_PASSWORD_OMADA
      remoteRef:
        key: MONGODB_USERS_CREDENTIALS_PASSWORD_OMADA
