# Ref: https://www.manelrodero.com/blog/instalacion-de-hacs-en-home-assistant-docker
# Ref: https://hacs.xyz/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada-controller

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: omada-controller
  meta.helm.sh/release-namespace: omada-controller

images:
- name: mbentley/omada-controller
  newTag: "5.13"

resources:
  - ../base
  - externalsecret-mongodb-user-credentials.yaml
  - certificate.yaml
  - ingress.yml

patches:
  - path: overlays/service.yml
