kind: Secret
apiVersion: v1
metadata:
  name: wg-secret
type: Opaque
data:
  # Generate and encode the server private key: `wg genkey | base64`
  privatekey: YUkreXlLcVY5VkU3YjEwZnZIN3hucnhrU2FHUjdadEh0ci9qa09kL1NITT0=