# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
# Ref: https://nicolasmarimon.com/blog/3


defaultPodOptions:
  labels:
    sidecar.istio.io/inject: "true"
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1002
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

controllers:

  application:
    type: deployment
    replicas: 1

    containers:
      main:
        image:
          repository: ghcr.io/qbittorrent/docker-qbittorrent-nox
          tag: 5.1.2-2

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: [ "ALL" ] }

        envFrom:
          - configMapRef:
              identifier: environment

        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            memory: 8Gi

persistence:
  config:
    existingClaim: "qbittorrent-config-pvc"
    globalMounts:
      - path: /config
        readOnly: false

  downloads:
    enabled: true
    type: custom
    volumeSpec:
      nfs:
        server: storage-01.internal.place
        path: "/mnt/pool0/shared/media.nfs/downloads"
        readOnly: false
    advancedMounts:
      application:
        main:
          - path: /data/downloads
            readOnly: false
            mountPropagation: None

configMaps:
  environment:
    enabled: true
    annotations: {}
    data:
      TZ: Europe/London
      QBT_WEBUI_PORT: "8080"
      QBT_TORRENTING_PORT: "6881"
      QBT_LEGAL_NOTICE: "confirm"

service:
  qbittorrent:
    controller: application
    type: ClusterIP
    ports:
      webui:
        port: 8080
        protocol: TCP

      bittorrent:
        port: 6881
        protocol: TCP

      bittorrent-udp:
        port: 6881
        protocol: UDP

rawResources:
  config-pvc:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      spec:
        storageClassName: "standard-nfs"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1G

  public-entrance:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    spec:
      spec:
        hostnames:
          - qbittorrent.tools.internal.place
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: gateway-api-extra-gateway-production
            namespace: istio
            sectionName: https-terminate
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: qbittorrent
                port: 8080
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /

  external-auth-check:
    enabled: true
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    spec:
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: qbittorrent
        action: CUSTOM
        provider:
          name: oauth2-proxy
        rules:
          - to:
            - operation:
                ports: [ "8080" ]
                hosts: [ "*.tools.internal.place" ]
