# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml


defaultPodOptions:
  labels: {}
  annotations: {}

controllers:

  application:
    type: deployment
    replicas: 1

    labels: {}
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        image:
          repository: b4bz/homer
          tag: latest
          pullPolicy: Always

configMaps:
  configuration:
    enabled: true
    annotations: {}
    data:
      config.yml: |
        # Homepage configuration
        # See https://fontawesome.com/search for icons options
        
        title: "Home Dashboard"        
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homer.png"
        header: true # Set to false to hide the header
        footer: false
        columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
        defaults:
          layout: columns # Either 'columns', or 'list'
          colorTheme: auto # One of 'auto', 'light', or 'dark'
        
        # Optional theming
        theme: default # 'default' or one of the themes available in 'src/assets/themes'.
        
        # Optional message
        message:
          # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
          # mapping: # allows to map fields from the remote format to the one expected by Homer
          #   title: 'id' # use value from field 'id' as title
          #   content: 'value' # value from field 'value' as content
          # refreshInterval: 10000 # Optional: time interval to refresh message
          #
          # Real example using chucknorris.io for showing Chuck Norris facts as messages:
          # url: https://api.chucknorris.io/jokes/random
          # mapping:
          #   title: 'id'
          #   content: 'value'
          # refreshInterval: 10000
          #style: "is-warning"
          #title: "Optional message!"
          #icon: "fa fa-exclamation-triangle"
          # The content also accepts HTML content, so you can add divs, images or whatever you want to make match your needs.
          #content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        
        # Upper navbar
        links:
          - name: "Dashboard Icons"
            #icon: "fab fa-github"
            url: "https://dashboardicons.com/"
            target: "_blank"
          #- name: "link 2"
          #  icon: "fas fa-book"
          #  url: "https://github.com/bastienwirtz/homer"
          # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
          # see url field and assets/page.yml used in this example:
          #- name: "Second Page"
          #  icon: "fas fa-file-alt"
          #  url: "#page2"
        
        # Services
        # First level array represents a group.
        # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
        services:
          - name: "Infrastructure"
            icon: "fa-solid fa-server"
            # class: "highlight-purple" # Optional css class to add on the service group. 
            items:
              - name: "Router"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/opnsense.png"
                subtitle: "Opnsense"
                tag: "router"
                keywords: "infrastructure router"
                url: "https://router-01.internal.place"
                target: "_blank"
        
              - name: "Hypervisor"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cockpit.png"
                subtitle: "Compute 10"
                tag: "hypervisor"
                keywords: "infrastructure hypervisor compute"
                url: "https://compute-10.internal.place:9090"
                target: "_blank"
        
              - name: "Hypervisor"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cockpit.png"
                subtitle: "Compute 20"
                tag: "hypervisor"
                keywords: "infrastructure hypervisor compute"
                url: "https://compute-20.internal.place:9090"
                target: "_blank"
        
              - name: "NAS"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/truecommand.png"
                subtitle: "Storage 01"
                tag: "NAS"
                keywords: "infrastructure nas storage"
                url: "https://storage-01.internal.place"
                target: "_blank"
        
              - name: "Omada Controller"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/omada.png"
                subtitle: "Omada Controller GUI"
                tag: "wifi"
                keywords: "infrastructure security"
                url: "https://omada-controller.tools.internal.place"
                target: "_blank"
        
          - name: "Security"
            icon: "fa-solid fa-shield-halved"
            items:
              - name: "Keycloak"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/keycloak.png"
                subtitle: "Keycloak GUI"
                tag: "identity"
                keywords: "security identity"
                url: "https://keycloak.tools.internal.place"
                target: "_blank"
        
              - name: "Vaultwarden"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitwarden.png"
                subtitle: "Credentials Vault"
                tag: "credentials"
                keywords: "security credentials vault"
                url: "https://vaultwarden.tools.internal.place"
                target: "_blank"
      
          - name: "Home Automation"
            icon: "fa-solid fa-robot"
            items:     
              - name: "Congatudo"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/valetudo.png"
                subtitle: "Robot GUI"
                tag: "comfort"
                keywords: "applications comfort domotic"
                url: "https://congatudo.tools.internal.place"
                target: "_blank"
        
              - name: "Home Assistant"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png"
                subtitle: "Home Assistant GUI"
                tag: "comfort"
                keywords: "applications comfort domotic"
                url: "https://home-assistant.tools.internal.place"
                target: "_blank"
        
          - name: "Entertainment"
            icon: "fa-solid fa-photo-film"
            items:
              - name: "Qbittorrent"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/qbittorrent.png"
                subtitle: "Torrent Manager"
                tag: "entertainment"
                keywords: "applications entertainment torrent"
                url: "https://qbittorrent.tools.internal.place"
                target: "_blank"
        
              - name: "BitMagnet"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitmagnet.png"
                subtitle: "DHT Crawler"
                tag: "entertainment"
                keywords: "applications entertainment torrent"
                url: "https://bitmagnet.tools.internal.place"
                target: "_blank"
        
              - name: "Prowlarr"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prowlarr.png"
                subtitle: "Indexers Manager"
                tag: "entertainment"
                keywords: "applications entertainment torrent"
                url: "https://prowlarr.tools.internal.place"
                target: "_blank"
        
              - name: "Radarr"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/radarr.png"
                subtitle: "Movies Manager"
                tag: "comfort"
                keywords: "applications entertainment movies"
                url: "https://radarr.tools.internal.place"
                target: "_blank"
        
              - name: "Sonarr"
                logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sonarr.png"
                subtitle: "TV Shows Manager"
                tag: "comfort"
                keywords: "applications entertainment shows"
                url: "https://sonarr.tools.internal.place"
                target: "_blank"

persistence:
  configuration:
    enabled: true
    name: "homer"
    type: configMap
    advancedMounts:
      application:
        main:
          - path: /www/assets/config.yml
            readOnly: true
            mountPropagation: None
            subPath: config.yml

service:
  gui:
    controller: application
    type: ClusterIP
    ports:
      http:
        port: 8080
        protocol: TCP

# Some stuff is not covered by this chart
rawResources:

  public-entrance:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    spec:
      spec:
        hostnames:
          - home.tools.internal.place
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: gateway-api-extra-gateway-production
            namespace: istio
            sectionName: https-terminate
        rules:
          - backendRefs: &mainBackendRef
              - group: ""
                kind: Service
                name: homer
                port: 8080
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /