apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congatudo

commonLabels:
  app.kubernetes.io/name: congatudo

resources:
  - namespace.yaml
  - configmap-config.yaml
  - deployment.yaml
  - service.yaml
  - service-exposed.yaml
