# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml


# Some stuff is not covered by this chart
rawResources:
  postgres-credentials:
    enabled: true
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    spec:
      spec:
        secretStoreRef: &secretStoreRefCr
          kind: ClusterSecretStore
          name: gitlab-secret-store
        target:
          name: keycloak-postgres-credentials
          template:
            engineVersion: v2
            data:
              # Password for user 'postgres', which is usually the main admin
              # Used by Postgres and Pgpool en env vars: PGPOOL_POSTGRES_PASSWORD, POSTGRES_PASSWORD
              postgres-password: "{{ `{{ .KEYCLOAK_PG_PASSWORD_USER_POSTGRES }}` }}"

        data:
          - secretKey: KEYCLOAK_PG_PASSWORD_USER_POSTGRES
            remoteRef:
              key: KEYCLOAK_PG_PASSWORD_USER_POSTGRES
