# Bitnami Postgres HA Helm chart
# Ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/values.yaml


nameOverride: &postgresNameOverrideSpec keycloak-postgres
fullnameOverride: *postgresNameOverrideSpec

# TODO
persistence:
  enabled: true
  storageClass: "do-block-storage-retain"
  size: 5Gi

auth:
  existingSecret: "keycloak-postgres-credentials"

primary:
  resources:
    requests: &postgresResourcesRequestsSpec
      memory: 500Mi
      cpu: 500m
    limits: *postgresResourcesRequestsSpec
