# TODO
data "gitlab_project_variable" "instance_access_compute_10_username" {
  project           = var.GITLAB_VARIABLES_PROJECT_ID
  environment_scope = var.GITLAB_VARIABLES_ENVIRONMENT

  key     = "INSTANCE_ACCESS_COMPUTE_10_USERNAME"
}

data "gitlab_project_variable" "instance_access_compute_10_password" {
  project           = var.GITLAB_VARIABLES_PROJECT_ID
  environment_scope = var.GITLAB_VARIABLES_ENVIRONMENT

  key     = "INSTANCE_ACCESS_COMPUTE_10_PASSWORD"
}

data "gitlab_project_variable" "instance_access_compute_10_host" {
  project           = var.GITLAB_VARIABLES_PROJECT_ID
  environment_scope = var.GITLAB_VARIABLES_ENVIRONMENT

  key     = "INSTANCE_ACCESS_COMPUTE_10_HOST"
}

# TODO
locals {
  
  disk_image_url = "https://cloud-images.ubuntu.com/releases/23.04/release/ubuntu-23.04-server-cloudimg-amd64.img"

  # Globals definition
  globals = {

    # Configuration for SSH connection parameters
    ssh_connection = {
      host     = data.gitlab_project_variable.instance_access_compute_10_host.value
      username = data.gitlab_project_variable.instance_access_compute_10_username.value
      password = data.gitlab_project_variable.instance_access_compute_10_password.value
      mode     = "password"
    }

    # Parameters related to those files used/thrown at some point on VM creation
    io_files = {

      # Path to the folder containing SSH keys authorized in all the VMs
      external_ssh_keys_path = "./files/input/external-ssh-keys"

      # Path to the folder where instances' autogenerated SSH keys will be stored
      instances_ssh_keys_path = "./files/output"
    }
  }

  # Networks definition
  networks = {

    external0 = {
      mode = "macvtap"
      interface = "enp1s0"
      dhcp_address_blocks = ["192.168.2.10/28"]
      gateway_address = "192.168.2.1"
    }
  }

  # Instance basic definition.
  # WARNING: Choose IP a address inside the right subnet
  instances = {

    # Define the masters
    kube-master-0 = {
      diskimage = local.disk_image_url

      vcpu   = 4
      memory = 4 * 1024
      disk   = 20000000000

      networks = [
        {
          name    = "external0"
          address = "192.168.2.11/24"
          mac     = "DA:C8:20:7A:37:BF"
        }
      ]
    }

    # Define the workers
    kube-worker-0 = {
      diskimage = local.disk_image_url

      vcpu   = 6
      memory = 20 * 1024
      disk   = 20000000000

      networks = [
        {
          name    = "external0"
          address = "192.168.2.16/24"
          mac     = "BE:FE:37:D8:6B:AB"
        }
      ]
    }
  }
}
