locals {
  
  disk_image_url = "https://cloud-images.ubuntu.com/releases/23.04/release/ubuntu-23.04-server-cloudimg-amd64.img"

  # Globals definition
  globals = {

    # Configuration for SSH connection parameters
    ssh_connection = {
      host     = var.SSH_HOST
      username = var.SSH_USERNAME

      password = var.SSH_PASSWORD
      #key_path = var.SSH_KEY_PATH
      mode     = "password"
      #mode     = "key"
    }

    # Parameters related to those files used/thrown at some point on VM creation
    io_files = {

      # Path to the folder containing SSH keys authorized in all the VMs
      external_ssh_keys_path = "./files/input/external-ssh-keys"

      # Path to the folder where instances' autogenerated SSH keys will be stored
      instances_ssh_keys_path = "./files/output"
    }

    # Parameters related to the installable OS on VMs creation
    os = {

      # URL to the .img file. Use a Linux distro supporting Cloud Init
      image_url = {
        x86_64 = "https://cloud-images.ubuntu.com/releases/23.04/release/ubuntu-23.04-server-cloudimg-amd64.img"
        aarch64 = "https://cloud-images.ubuntu.com/releases/23.04/release/ubuntu-23.04-server-cloudimg-arm64.img"
      }

    }
  }

  # Networks definition
  # Possible types: nat, macvtap
  networks = {

    # Configuration for a macvtap
    external0 = {
      # Type of network
      # Possible values: nat, macvtap
      mode = "macvtap"

      # Host physical interface to attach
      # the autogenerated virtual interface
      interface = "eth0"

      # Assignable IP address blocks in CIDR notation
      # Example: [IPv4/CIDR] -> /28 prefix make assignable 16 IPs
      dhcp_address_blocks = ["192.168.2.80/28"]

      # Address to the gateway
      gateway_address = "192.168.2.1"
    }
  }

  # Instance basic definition.
  # WARNING: Choose IP a address inside the right subnet
  instances = {

    # Define the masters
    kube-master-0 = {
      #diskimage = local.disk_image_url
      vcpu   = 4
      memory = 8192
      disk   = 20000000000
      networks = [
        {
          name    = "external0"
          address = "192.168.2.10/24"
          mac     = "DA:C8:20:7A:37:BF"
        }
      ]
    }

    kube-master-1 = {
      #diskimage = local.disk_image_url
      vcpu   = 4
      memory = 8192
      disk   = 20000000000
      networks = [
        {
          name    = "external0"
          address = "192.168.2.11/24"
          mac     = "DA:C8:20:7A:37:BF"
        }
      ]
    }

    kube-master-2 = {
      #diskimage = local.disk_image_url
      vcpu   = 4
      memory = 8192
      disk   = 20000000000
      networks = [
        {
          name    = "external0"
          address = "192.168.2.12/24"
          mac     = "DA:C8:20:7A:37:BF"
        }
      ]
    }

    # Define the workers
    kube-worker-0 = {
      #diskimage = local.disk_image_url
      vcpu   = 8
      memory = 16384
      disk   = 20000000000
      networks = [
        {
          name    = "external0"
          address = "192.168.2.13/24"
          mac     = "BE:FE:37:D8:6B:AB"
        }
      ]
    }

    kube-worker-1 = {
      #diskimage = local.disk_image_url
      vcpu   = 2
      memory = 16384
      disk   = 20000000000
      networks = [
        {
          name    = "external0"
          address = "192.168.2.14/24"
          mac     = "BE:FE:37:D8:6B:AB"
        }
      ]
    }

  }
}
