# Ref: https://forum.opnsense.org/index.php?topic=15756.0
# Ref: https://blog.xirion.net/posts/metallb-opnsense/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congatudo

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: congatudo
  meta.helm.sh/release-namespace: congatudo

commonLabels:
  cluster: kubernetes-01

resources:
  - ../base
  - ingress.yaml
