apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {}
  template:
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: matter-server
        image: "ghcr.io/home-assistant-libs/python-matter-server:stable"
        imagePullPolicy: IfNotPresent
        ports:
          - name: websockets
            containerPort: 5580
            protocol: TCP
        volumeMounts:
          - name: matter-data
            mountPath: /data
          # TODO
          - name: rundbus
            mountPath: /run/dbus
            readOnly: true
      volumes:
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-server-data
        - name: rundbus
          hostPath:
            path: /run/dbus