---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  path: ./kubernetes/applications/cert-manager/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system