apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/applications/cert-manager/operator
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - ./kubernetes/applications/cert-manager/operator/values.yaml
        - ./kubernetes/applications/cert-manager/operator/values-kubernetes-01.yaml

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
    remediation: &remediation
      retries: 10
      remediateLastFailure: true
  upgrade:
    remediation: *remediation