# DISCLAIMER: THESE VALUES ARE FOR PRODUCTION PURPOSES ONLY.
# PLEASE, DON'T DO DIRTY THINGS

immich:

  immich:
    persistence:
      library:
        existingClaim: immich-data

    configuration: {}
    # trash:
    #   enabled: false
    #   days: 30
    # storageTemplate:
    #   enabled: true
    #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

  postgresql:
    enabled: true
    image:
      repository: tensorchord/pgvecto-rs
      tag: pg14-v0.2.0
    global:
      storageClass: standard-nfs
      postgresql:
        auth:
          username: immich
          database: immich
          password: immich
    primary:
      containerSecurityContext:
        readOnlyRootFilesystem: false

      resourcesPreset: "small"

      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION cube;
            CREATE EXTENSION earthdistance;
            CREATE EXTENSION vectors;

  redis:
    enabled: true
    global:
      storageClass: standard-nfs
    architecture: standalone
    auth:
      enabled: false

  server:
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          # proxy-body-size is set to 0 to remove the body limit on file uploads
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host "immich.tools.internal.place"
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: immich-server
                  port:
                    name: "http"
        tls:
        - hosts:
            - *host
          secretName: immich-tls