apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autoheater-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: autoheater-credentials
    creationPolicy: Owner

  data:
    - secretKey: TAPO_SMARTPLUG_USERNAME
      remoteRef:
        key: AUTOHEATER_TAPO_SMARTPLUG_USERNAME

    - secretKey: TAPO_SMARTPLUG_PASSWORD
      remoteRef:
        key: AUTOHEATER_TAPO_SMARTPLUG_PASSWORD