apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoheater

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: autoheater
  meta.helm.sh/release-namespace: autoheater

replicas:
  - name: autoheater
    count: 1

images:
  - name: ghcr.io/achetronic/autoheater:latest
    newTag: v0.5.0

resources:
  - ../base
  - configmap.yaml
  - configmap-env.yaml
