apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoheater

commonLabels:
  cluster: kubernetes-01

replicas:
  - name: autoheater
    count: 1

images:
  - name: ghcr.io/achetronic/autoheater:latest
    newTag: v0.3.1-alpha3

resources:
  - ../base
  - configmap.yaml
  - configmap-env.yaml
