apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forecastle

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
      app.kubernetes.io/name: forecastle
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: forecastle-extra
  meta.helm.sh/release-namespace: forecastle

resources:
  # Infrastructure
  - compute-10.yaml
  - compute-20.yaml
  - opnsense.yaml
  - storage-01.yaml

  # Applications
  - congatudo.yaml
  - home-assistant.yaml
  - omada-controller.yaml
  - vaultwarden.yaml
