# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
# Ref: https://bitmagnet.io/setup/configuration.html


defaultPodOptions:
  labels: {}
    #sidecar.istio.io/inject: "true"
  annotations: {}

controllers:

  application:
    type: deployment
    replicas: 1
    containers:
      main:
        image:
          repository: ghcr.io/bitmagnet-io/bitmagnet
          tag: latest
          pullPolicy: Always
        args:
          - worker
          - run
          - --keys=http_server
          - --keys=queue_server
          - --keys=dht_crawler
        env:
          POSTGRES_HOST:
            value: postgres-bitmagnet-cluster-00-rw.postgres.svc
          POSTGRES_PORT:
            value: "5432"
          POSTGRES_NAME:
            value: app
          POSTGRES_USER:
            valueFrom:
              secretKeyRef:
                name: database-user-credentials
                key: username
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: database-user-credentials
                key: password
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 1Gi

persistence:
  config:
    existingClaim: "bitmagnet-config-pvc"
    globalMounts:
      - path: /root/.config/bitmagnet
        readOnly: false

service:
  bitmagnet:
    enabled: true
    controller: application
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 3333
        protocol: HTTP
        targetPort: 3333

      bittorrent-tcp:
        enabled: true
        port: 3334
        protocol: TCP
        targetPort: 3334

      bittorrent-udp:
        enabled: true
        port: 3334
        protocol: UDP
        targetPort: 3334

rawResources:
  config-pvc:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      spec:
        storageClassName: "standard-nfs"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1G

  public-entrance:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    spec:
      spec:
        hostnames:
          - bitmagnet.tools.internal.place
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: gateway-api-extra-gateway-production
            namespace: istio
            sectionName: https-terminate
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: bitmagnet
                port: 3333
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /
