# DISCLAIMER: THESE VALUES ARE FOR PRODUCTION PURPOSES ONLY.
# PLEASE, DON'T DO DIRTY THINGS

ingress-nginx:
  controller:

    # Resources for Ingress' pods
    # Ideally, no limits needed
    resources:
      requests:
        cpu: 200m
        memory: 200Mi

    # Assign a fixed IP for the ingress controller's LB
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: &loadbalancerIP 192.168.2.60
      #loadBalancerIP: *loadbalancerIP
