# DISCLAIMER: THESE VALUES ARE FOR PRODUCTION PURPOSES ONLY.
# PLEASE, DON'T DO DIRTY THINGS

ingress-nginx:
  controller:
    # Mark the created ingressClass as the default in the cluster
    ingressClassResource:
      default: true

    # Resources for Ingress pods
    # Ideally, no limits needed
    resources:
      requests:
        cpu: 200m
        memory: 200Mi

    # Enforce the reliability enabling HA for the controller
    autoscaling:
      enabled: true
      maxReplicas: 20
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 180
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 2
              periodSeconds: 60

    # Enable SSL connections directly to the services when requested on annotations
    extraArgs:
      enable-ssl-passthrough: "true"

    # Assign a fixed IP for the ingress controller's LB
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: &loadbalancerIP 192.168.2.60
      #loadBalancerIP: *loadbalancerIP
