apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: democratic-csi
  targetNamespace: democratic-csi
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/applications/democratic-csi
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - ./kubernetes/applications/democratic-csi/values.yaml
        - ./kubernetes/applications/democratic-csi/values-kubernetes-01.yaml

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
    remediation: &remediation
      retries: 10
      remediateLastFailure: true
  upgrade:
    remediation: *remediation