apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoheater
spec:
  replicas: 1
  selector:
    matchLabels: {}
  strategy:
    type: Recreate
  template:
    spec:
      hostname: autoheater-hostname
      restartPolicy: Always
      containers:
        - name: autoheater
          image: ghcr.io/achetronic/autoheater:latest
          resources: {}
          args:
            - run
            - --config
            - /tmp/autoheater.yaml

          envFrom:
            - configMapRef:
                name: autoheater-config-env

          volumeMounts:
            - mountPath: /tmp/autoheater.yaml
              subPath: autoheater.yaml
              name: autoheater-data

      volumes:
        - name: autoheater-data
          configMap:
            name: autoheater-config
