apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-driver-s3-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: csi-driver-s3-credentials
    creationPolicy: Owner

  data:
    - secretKey: endpoint
      remoteRef:
        key: CSI_S3_ENDPOINT

    - secretKey: accessKeyID
      remoteRef:
        key: CSI_S3_ACCESS_KEY_ID

    - secretKey: secretAccessKey
      remoteRef:
        key: CSI_S3_SECRET_ACCESS_KEY

