apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-driver-s3

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: csi-driver-s3-extra
  meta.helm.sh/release-namespace: csi-driver-s3

resources:
  - externalsecret-csi-driver-s3-credentials.yaml
