apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
data:
  # External IP or domain name for docker host. Used in server mode.
  # If set to auto, the container will try to determine and set the external IP automatically
  SERVERURL: "gateway.internal.place"

  # Number of peers to create confs for.
  # Required for server mode. Can also be a list of names: myPC,myPhone,myTablet (alphanumeric only)
  # Peer 1: Alby Hernández
  # Peer 2: Jose Agustin
  # Peer 3: Milagro Fumero
  # Peer 4: Itahisa Hernandez
  # Peer 5: Andrea Malvar
  # To see connection configuration for a peer: k exec -it -n wireguard pod/<POD> -- /app/show-peer <PEER NUMBER>
  PEERS: "5"

  # DNS server set in peer/client configs (can be set as 8.8.8.8). Used in server mode.
  # Defaults to auto, which uses wireguard docker host's DNS via included CoreDNS forward.
  PEERDNS: "10.96.100.10"

  # The IPs/Ranges that the peers will be able to reach using the VPN connection.
  # If not specified the default value is: '0.0.0.0/0, ::0/0' This will cause ALL traffic to route through the VPN,
  # if you want split tunneling, set this to only the IPs you would like to use the tunnel
  # AND the ip of the server's WG ip, such as 10.13.13.1
  ALLOWEDIPS: "0.0.0.0/0, ::/0"

  # Internal subnet for the wireguard and server and peers (only change if it clashes)
  INTERNAL_SUBNET: "10.30.0.0"
