# Ref: https://dev.to/ivanmoreno/how-to-connect-with-kubernetes-internal-network-using-wireguard-48bh
# Ref: https://www.wireguardconfig.com/
# Ref: https://github.com/wg-easy/wg-easy

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard

commonLabels:
  cluster: kubernetes-01

replicas:
  - name: wireguard
    count: 3

resources:
  - ../base

patches:
  - path: service-patch.yaml
    target:
      kind: Service

  - path: configmap-patch.yaml
    target:
      kind: ConfigMap


---
# To see the peer connection config: k exec -it -n wireguard pod/<POD> -- /app/show-peer <PEER NUMBER>