# Ref: https://dev.to/ivanmoreno/how-to-connect-with-kubernetes-internal-network-using-wireguard-48bh
# Ref: https://github.com/wg-easy/wg-easy

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blocky

commonLabels:
  cluster: kubernetes-01

replicas:
  - name: blocky
    count: 3

resources:
  - ../base
  - configmap.yaml
  - service.yaml
