# Ref: https://dev.to/ivanmoreno/how-to-connect-with-kubernetes-internal-network-using-wireguard-48bh
# Ref: https://github.com/wg-easy/wg-easy

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blocky

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  meta.helm.sh/release-name: blocky
  meta.helm.sh/release-namespace: blocky

replicas:
  - name: blocky
    count: 3

resources:
  - ../base
  - configmap.yaml
  - service.yaml
