---
## MANUALLY GENERATED
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kubernetes-01
spec:
  hosts:

    # Config for masters
    - ssh:
        address: compute-01.internal.place
        user: root
        port: 22
        keyPath: null
      role: controller

    - ssh:
        address: compute-02.internal.place
        user: root
        port: 22
        keyPath: null
      role: controller

    - ssh:
        address: compute-03.internal.place
        user: root
        port: 22
        keyPath: null
      role: controller

    # Config for workers
    - ssh:
        address: compute-04.internal.place
        user: root
        port: 22
        keyPath: null
      role: worker
      privateInterface: eth0
      #installFlags:
      #  - --disable-components=metrics-server

    - ssh:
        address: compute-05.internal.place
        user: root
        port: 22
        keyPath: null
      role: worker
      privateInterface: eth0
      #installFlags:
      #  - --disable-components=metrics-server

  # Config related to K0s itself
  k0s:
    version: 1.27.4+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          externalAddress: kubernetes-01.internal.place
        #          externalAddress: <load balancer public ip address>
        #          sans:
        #            - <load balancer public ip address>
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          provider: calico
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12

          # TODO
          kubeProxy:
            disabled: false
            mode: ipvs
            ipvs:
              strictARP: true

          # TODO
          # Ref: https://docs.k0sproject.io/v0.12.0/configuration/#specnetworkcalico
          calico:
            mode: vxlan
            vxlanPort: 4789
            vxlanVNI: 4096
            mtu: 1450
            wireguard: false
            flexVolumeDriverPath: /usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
            withWindowsNodes: false

        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false