apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
spec:
  secretName: vaultwarden-tls
  dnsNames:
    - vaultwarden.tools.internal.place
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io