# Ref: https://forum.opnsense.org/index.php?topic=15756.0
# Ref: https://blog.xirion.net/posts/metallb-opnsense/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

labels:
  - pairs:
      app.kubernetes.io/managed-by: Helm
    includeSelectors: false
    includeTemplates: false

  - pairs:
      cluster: kubernetes-01
    includeSelectors: false
    includeTemplates: false

commonAnnotations:
  meta.helm.sh/release-name: vaultwarden
  meta.helm.sh/release-namespace: vaultwarden

images:
  - name: vaultwarden/server:latest
    newTag: 1.33.2

replicas:
  - name: vaultwarden
    count: 1

resources:
  - ../base
  - configmap.yaml
  - certificate.yaml
  - ingress.yaml
