# Ref: https://forum.opnsense.org/index.php?topic=15756.0
# Ref: https://blog.xirion.net/posts/metallb-opnsense/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

images:
  - name: vaultwarden/server:latest
    newTag: 1.32.1

replicas:
  - name: vaultwarden
    count: 1

resources:
  - ../base
  - configmap.yaml
  - certificate.yaml
  - ingress.yaml
