apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
    includeSelectors: true
    includeTemplates: true

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

  - pvc-backup.yaml
  - cronjob-backup.yaml