apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

commonLabels:
  app.kubernetes.io/name: vaultwarden

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  #- poddisruptionbudget.yaml
