apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant
spec:
  secretName: home-assistant-tls
  dnsNames:
    - home-assistant.tools.internal.place
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
