apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
data:
  # Ref: https://github.com/arsaboo/homeassistant-config/blob/master/configuration.yaml
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    # Text to speech
    tts:
      - platform: google_translate

    # Allows you to issue voice commands from the frontend in enabled browsers
    conversation:

    #automation: !include automations.yaml
    #script: !include scripts.yaml
    #scene: !include scenes.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - 10.90.0.0/16
        
    # Add links to side panel
    # Ref: https://www.home-assistant.io/integrations/panel_iframe/
    panel_iframe:
      zigbee2mqtt:
        title: "Zigbee 2 MQTT"
        icon: mdi:zigbee
        url: "https://zigbee2mqtt.tools.internal.place:8080"

    #hue:
    #  bridges:
    #    - host: 192.168.2.229
    #      allow_hue_groups: false
    #      allow_unreachable: true

#    rest_command:
#      get_json_data:
#        url: "https://raw.githubusercontent.com/jorgeatgu/apaga-luz/main/public/data/canary_price.json"

#  automations.yaml: |
#    []
#
#  scripts.yaml: |
#    []
