apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  selector: {}
  template:
    spec:
      # Enable IP forwarding on the node
      initContainers:
        - name: sysctls
          image: busybox
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true

      # Deploy Wireguard containers
      containers:
        - name: wireguard
          image: ghcr.io/linuxserver/wireguard
          envFrom:
            - configMapRef:
                name: wireguard-configmap

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true

          volumeMounts:
            - name: wg-config
              mountPath: /config
            - name: host-volumes
              mountPath: /lib/modules

          ports:
            - containerPort: 51820
              protocol: UDP

          resources: {}

      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wireguard-data

        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory
