# Ref: https://docs.linuxserver.io/images/docker-wireguard/#docker-compose-recommended-click-here-for-more-info

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  selector: {}
  template:
    spec:
      # TODO
      initContainers:
        - name: sysctls
          image: busybox
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.conf.all.src_valid_mark=1
          securityContext: &securityContextSpec
            capabilities:
              add:
                - NET_ADMIN
            privileged: true

      # Deploy Wireguard containers
      containers:
        - name: wireguard
          image: ghcr.io/linuxserver/wireguard
          envFrom:
            - configMapRef:
                name: wireguard-configmap
          securityContext: *securityContextSpec
          volumeMounts:
            - name: wg-config
              mountPath: /config
          ports:
            - containerPort: 51820
              protocol: UDP
          resources: {}
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wireguard-data
