# Ref: https://dev.to/ivanmoreno/how-to-connect-with-kubernetes-internal-network-using-wireguard-48bh
# Ref: https://www.wireguardconfig.com/
# Ref: https://github.com/wg-easy/wg-easy

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: wireguard

resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
