kind: Service
apiVersion: v1
metadata:
  name: wireguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: &loadbalancerIP 192.168.2.63
spec:
  type: LoadBalancer
  ports:
    - port: 31820
      protocol: UDP
      targetPort: 51820
  selector: {}

  # Deprecated, not dual-stack, no alternative yet
  # Ref: https://stackoverflow.com/questions/73750700/what-is-the-replacement-for-the-deprecated-loadbalancerip-attribute-in-services
  #loadBalancerIP: *loadbalancerIP
