kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-data
spec:
  storageClassName: standard-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
