cluster:

  network:
    # The domain used by Kubernetes DNS.
    dnsDomain: cluster.local
    # The pod subnet CIDR.
    podSubnets:
      - 10.244.0.0/16
    # The service subnet CIDR.
    serviceSubnets:
      - 10.96.0.0/12

  controlPlane:
    endpoint: https://kubernetes-02.internal.place:6443
