apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: zigbee2mqtt

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yml

  - pvc-backup.yaml
  - cronjob-backup.yaml
