# Ref: https://github.com/stakater/Forecastle/blob/master/deployments/kubernetes/chart/forecastle/values.yaml
forecastle:

  forecastle:

    # TODO
    namespace: forecastle

    # TODO
    config:
      title: Homelab Ops
      crdEnabled: true
      namespaceSelector:
        any: true
        matchNames: []

    # TODO
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: &host home.tools.internal.place
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: forecastle-tls
