# Ref: https://github.com/backube/volsync/blob/main/helm/volsync/values.yaml

replicaCount: 2

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 64Mi

affinity: {}
