apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bucket-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: bucket-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: S3_ACCESS_KEY_ID_CNPG

    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: S3_SECRET_ACCESS_KEY_CNPG