apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
spec:
  secretName: immich-tls
  dnsNames:
    - immich.tools.internal.place
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
