# Ref: https://github.com/mbentley/docker-omada-controller/blob/master/docker-compose.yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: omada-controller-environment
data:
  #
  PUID: "508"
  PGID: "508"

  #
  MANAGE_HTTP_PORT: "8088"
  MANAGE_HTTPS_PORT: "8043"
  PORTAL_HTTP_PORT: "8088"
  PORTAL_HTTPS_PORT: "8843"

  #
  PORT_APP_DISCOVERY: "27001"
  PORT_DISCOVERY: "29810"

  # V1
  PORT_MANAGER_V1: "29811"
  PORT_ADOPT_V1: "29812"
  PORT_UPGRADE_V1: "29813"

  # V2
  PORT_MANAGER_V2: "29814"
  PORT_TRANSFER_V2: "29815"

  PORT_RTTY: "29816"

  #
  SHOW_SERVER_LOGS: "true"
  SHOW_MONGODB_LOGS: "false"
  SSL_CERT_NAME: "tls.crt"
  SSL_KEY_NAME: "tls.key"
  TZ: "Etc/UTC"
