apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: omada-controller

# Ref: https://github.com/mbentley/docker-omada-controller/blob/master/docker-compose.yml
# Ref: https://github.com/mbentley/docker-omada-controller/issues/356
resources:
  - pvc-omada-data.yml
  - pvc-omada-logs.yml
  - configmap-env.yaml
  - deployment.yml
  - service.yml
